name: fix-profile-action
description: Fixes env key removing a profile name.
branding:
  icon: edit
  color: purple
inputs:
  profile:
    description: Profile name.
    required: true
  ignore-case:
    description: "Ignoring case(boolean, default: true)"
runs:
  using: composite
  steps:
    - name: Run
      env:
        PROFILE: ${{ inputs.profile }}
        IGNORE_CASE: ${{ inputs.ignore-case }}
      shell: bash
      run: |
        declare profile
        if [[ -z "${PROFILE}" ]] ; then
          exit 1
        elif [[ -z "${IGNORE_CASE}" || "${IGNORE_CASE}" == "true" ]] ; then
          profile="${PROFILE^^}"
        else
          profile="${PROFILE}"
        fi
        env | grep "${profile}" | grep -v "^PROFILE=" | while read line; do
          key=$(echo "${line}" | cut -d'=' -f1 | sed -e "s/_${profile}//g" -e "s/${profile}_//g")
          value=$(echo "${line}" | cut -d'=' -f2-)
          echo "new env ${key}"
          echo "${key}=${value}" >> $GITHUB_ENV
        done
